//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DJobItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DJobItem()
        {
            this.DJobTimings = new HashSet<DJobTiming>();
        }
    
        public int JobItemId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Description { get; set; }
        public Nullable<long> Time { get; set; }
        public Nullable<int> EstimateId { get; set; }
        public string DeveloperCode { get; set; }
        public Nullable<int> RequestorId { get; set; }
    
        public virtual DCustomer DCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DJobTiming> DJobTimings { get; set; }
        public virtual DRequestor DRequestor { get; set; }
    }
}
